version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/root/back/views
      override: yes
    # - source: /
    #   destination: /home/ubuntu/front_build
# hooks:
#     ApplicationStop:
#         - location: scripts/applicationStop.sh
#     AfterInstall:
#         - location: scripts/afterInstall.sh
